default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  # Main application database
  primary:
    adapter: postgresql
    database: website
    username: postgres
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: localhost

  # Published game account data
  game_accounts:
    adapter: postgresql
    database: game_accounts
    username: postgres
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: localhost
    migrations_paths: db/game_accounts_migrate

production:
  # Main application database - production
  primary:
    adapter: postgresql
    database: website_production
    username: postgres
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: localhost

  # Published game account data - production
  game_accounts:
    adapter: postgresql
    database: game_accounts_production
    username: postgres
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: localhost
    migrations_paths: db/game_accounts_migrate
